### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by sajidahmed12** [SharukhFardin/CSE311.9L_Summer20_RAH1_-GROUP-I-#1]
So Far your Proposal is quite  Good. My suggestion is to add one more Entity like Hospitals where you can give emergency blood if needed as well as collect bloods from them.

**Comment by SharukhFardin** [comment]
Okay vaia. Keeping that in mind.

**Comment by SharukhFardin** [comment]
Vaia, we added hospital section as you said. So i'm closing the issue.
